package com.hatgroup.vchord.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LICENSE.
 */
public class License {

    private String active_code;

    public License() {
    }

    public License(String active_code) {
        this.active_code = active_code;
    }

    public String getActive_code() {
        return active_code;
    }

    public void setActive_code(String active_code) {
        this.active_code = active_code;
    }

}
