package com.hatgroup.vchord.entities;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SONG.
 */
public class Song implements Serializable{

    private Integer id;
    private String title;
    private String lyric;
    private Integer rhythm_id;
    private Integer level_id;
    private Integer melody_id;
    private String update_date;
    private String music_link;
    private Integer favorite;
    private String setting;
    private String unsigned_title;
    private String singer_name;
    private String unsigned_singer_name;
    private String composer_name;
    private String unsigned_composer_name;
    private String tone;

    public Song() {
    }

    public Song(Integer id) {
        this.id = id;
    }

    public Song(Integer id, String title, String lyric, Integer rhythm_id, Integer level_id, Integer melody_id, String update_date, String music_link, Integer favorite, String setting, String unsigned_title, String singer_name, String unsigned_singer_name, String composer_name, String unsigned_composer_name, String tone) {
        this.id = id;
        this.title = title;
        this.lyric = lyric;
        this.rhythm_id = rhythm_id;
        this.level_id = level_id;
        this.melody_id = melody_id;
        this.update_date = update_date;
        this.music_link = music_link;
        this.favorite = favorite;
        this.setting = setting;
        this.unsigned_title = unsigned_title;
        this.singer_name = singer_name;
        this.unsigned_singer_name = unsigned_singer_name;
        this.composer_name = composer_name;
        this.unsigned_composer_name = unsigned_composer_name;
        this.tone = tone;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getLyric() {
        return lyric;
    }

    public void setLyric(String lyric) {
        this.lyric = lyric;
    }

    public Integer getRhythm_id() {
        return rhythm_id;
    }

    public void setRhythm_id(Integer rhythm_id) {
        this.rhythm_id = rhythm_id;
    }

    public Integer getLevel_id() {
        return level_id;
    }

    public void setLevel_id(Integer level_id) {
        this.level_id = level_id;
    }

    public Integer getMelody_id() {
        return melody_id;
    }

    public void setMelody_id(Integer melody_id) {
        this.melody_id = melody_id;
    }

    public String getUpdate_date() {
        return update_date;
    }

    public void setUpdate_date(String update_date) {
        this.update_date = update_date;
    }

    public String getMusic_link() {
        return music_link;
    }

    public void setMusic_link(String music_link) {
        this.music_link = music_link;
    }

    public Integer getFavorite() {
        return favorite;
    }

    public void setFavorite(Integer favorite) {
        this.favorite = favorite;
    }

    public String getSetting() {
        return setting;
    }

    public void setSetting(String setting) {
        this.setting = setting;
    }

    public String getUnsigned_title() {
        return unsigned_title;
    }

    public void setUnsigned_title(String unsigned_title) {
        this.unsigned_title = unsigned_title;
    }

    public String getSinger_name() {
        return singer_name;
    }

    public void setSinger_name(String singer_name) {
        this.singer_name = singer_name;
    }

    public String getUnsigned_singer_name() {
        return unsigned_singer_name;
    }

    public void setUnsigned_singer_name(String unsigned_singer_name) {
        this.unsigned_singer_name = unsigned_singer_name;
    }

    public String getComposer_name() {
        return composer_name;
    }

    public void setComposer_name(String composer_name) {
        this.composer_name = composer_name;
    }

    public String getUnsigned_composer_name() {
        return unsigned_composer_name;
    }

    public void setUnsigned_composer_name(String unsigned_composer_name) {
        this.unsigned_composer_name = unsigned_composer_name;
    }

    public String getTone() {
        return tone;
    }

    public void setTone(String tone) {
        this.tone = tone;
    }

}
