package com.hatgroup.vchord.daos;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hatgroup.vchord.entities.*;

import com.hatgroup.vchord.daos.SongDao;
import com.hatgroup.vchord.daos.LevelDao;
import com.hatgroup.vchord.daos.RhythmDao;
import com.hatgroup.vchord.daos.MelodyDao;
import com.hatgroup.vchord.daos.LicenseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig songDaoConfig;
    private final DaoConfig levelDaoConfig;
    private final DaoConfig rhythmDaoConfig;
    private final DaoConfig melodyDaoConfig;
    private final DaoConfig licenseDaoConfig;

    private final SongDao songDao;
    private final LevelDao levelDao;
    private final RhythmDao rhythmDao;
    private final MelodyDao melodyDao;
    private final LicenseDao licenseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        songDaoConfig = daoConfigMap.get(SongDao.class).clone();
        songDaoConfig.initIdentityScope(type);

        levelDaoConfig = daoConfigMap.get(LevelDao.class).clone();
        levelDaoConfig.initIdentityScope(type);

        rhythmDaoConfig = daoConfigMap.get(RhythmDao.class).clone();
        rhythmDaoConfig.initIdentityScope(type);

        melodyDaoConfig = daoConfigMap.get(MelodyDao.class).clone();
        melodyDaoConfig.initIdentityScope(type);

        licenseDaoConfig = daoConfigMap.get(LicenseDao.class).clone();
        licenseDaoConfig.initIdentityScope(type);

        songDao = new SongDao(songDaoConfig, this);
        levelDao = new LevelDao(levelDaoConfig, this);
        rhythmDao = new RhythmDao(rhythmDaoConfig, this);
        melodyDao = new MelodyDao(melodyDaoConfig, this);
        licenseDao = new LicenseDao(licenseDaoConfig, this);

        registerDao(Song.class, songDao);
        registerDao(Level.class, levelDao);
        registerDao(Rhythm.class, rhythmDao);
        registerDao(Melody.class, melodyDao);
        registerDao(License.class, licenseDao);
    }
    
    public void clear() {
        songDaoConfig.getIdentityScope().clear();
        levelDaoConfig.getIdentityScope().clear();
        rhythmDaoConfig.getIdentityScope().clear();
        melodyDaoConfig.getIdentityScope().clear();
        licenseDaoConfig.getIdentityScope().clear();
    }

    public SongDao getSongDao() {
        return songDao;
    }

    public LevelDao getLevelDao() {
        return levelDao;
    }

    public RhythmDao getRhythmDao() {
        return rhythmDao;
    }

    public MelodyDao getMelodyDao() {
        return melodyDao;
    }

    public LicenseDao getLicenseDao() {
        return licenseDao;
    }

}
