package com.guitar.instructor.daos;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHORD_LIB.
 */
public class ChordLib {

    private String id;
    private String name;
    private String type;
    private String data;
    private String variation;

    public ChordLib() {
    }

    public ChordLib(String id) {
        this.id = id;
    }

    public ChordLib(String id, String name, String type, String data, String variation) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.data = data;
        this.variation = variation;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getVariation() {
        return variation;
    }

    public void setVariation(String variation) {
        this.variation = variation;
    }

}
