package com.guitar.instructor.daos;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.guitar.instructor.daos.SongDao;
import com.guitar.instructor.daos.ArtistDao;
import com.guitar.instructor.daos.LevelDao;
import com.guitar.instructor.daos.RhythmDao;
import com.guitar.instructor.daos.MelodyDao;
import com.guitar.instructor.daos.ChordLibDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 3): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        SongDao.createTable(db, ifNotExists);
        ArtistDao.createTable(db, ifNotExists);
        LevelDao.createTable(db, ifNotExists);
        RhythmDao.createTable(db, ifNotExists);
        MelodyDao.createTable(db, ifNotExists);
        ChordLibDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        SongDao.dropTable(db, ifExists);
        ArtistDao.dropTable(db, ifExists);
        LevelDao.dropTable(db, ifExists);
        RhythmDao.dropTable(db, ifExists);
        MelodyDao.dropTable(db, ifExists);
        ChordLibDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(SongDao.class);
        registerDaoClass(ArtistDao.class);
        registerDaoClass(LevelDao.class);
        registerDaoClass(RhythmDao.class);
        registerDaoClass(MelodyDao.class);
        registerDaoClass(ChordLibDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
